image: Visual Studio 2017
environment:
 nodejs_version: "8"
platform: x64
configuration: Release
install:
- ps: Install-Product node $env:nodejs_version $env:platform
- npm install -g node-gyp
build_script:
- node-gyp configure
- node-gyp build
- cd %APPVEYOR_BUILD_FOLDER%\build\Release\
- 7z a -tgzip say_hello_addon_win64.7z say_hello_addon.node
- cd %APPVEYOR_BUILD_FOLDER%
artifacts:
- path: build\Release\say_hello_addon_win64.7z
  name: say_hello_addon_win64.7z
deploy:
 description: 'windows release version'
 provider: GitHub
 branch: master    
 auth_token:
  secure: kW2dq5Hyg8WlsGniBQ7Xs9c0AM7teybE4HjQcig8Jaw4yeGvoOqkQ49wUTvmKL08
# '%appveyorGithub%'
 artifact: build\Release\say_hello_addon_win64.7z
 on:
  appveyor_repo_tag: false
  configuration: Release