image: Visual Studio 2017
environment:
 nodejs_version: "8"
platform: x64
configuration: Release
install:
- ps: Install-Product node $env:nodejs_version $env:platform
- npm install -g node-gyp
build: off
build_script:
- node-gyp configure
- node-gyp build
- cd %APPVEYOR_BUILD_FOLDER%\build\Release\
- 7z a -tgzip say_hello_addon_win64.tar.gz say_hello_addon.node
- cd %APPVEYOR_BUILD_FOLDER%
artifacts:
- path: build\Release\say_hello_addon_win64.tar.gz
  name: say_hello_addon_win64.tar.gz
deploy:
 provider: GitHub
 branch: master    
 auth_token: ${appveyorGithub}
 artifact: build\Release\say_hello_addon_win64.tar.gz
 on:
  appveyor_repo_tag: false
