image: Visual Studio 2017
environment:
 nodejs_version: "8"
platform: x64
configuration: Release
install:
 - ps: Install-Product node $env:nodejs_version $env:platform
 - npm install -g node-gyp
 - npm install -g node-pre-gyp
 - npm install -g mocha
build_script:
 - node-gyp configure
 - node-gyp build
 - copy %APPVEYOR_BUILD_FOLDER%\build\Release\say_hello_addon.node %APPVEYOR_BUILD_FOLDER%\bin
 - 7z a -ttar %APPVEYOR_BUILD_FOLDER%\build\Release\tmp.tar %APPVEYOR_BUILD_FOLDER%\bin
 - 7z a -tgzip %APPVEYOR_BUILD_FOLDER%\build\Release\say_hello_addon_win32.tar.gz %APPVEYOR_BUILD_FOLDER%\build\Release\tmp.tar
 
test_script:
 - npm test
  
artifacts:
 path: build\Release\say_hello_addon_win32.tar.gz
 name: say_hello_addon_win32.tar.gz
deploy:
 description: 'windows release version'
 provider: GitHub
 branch: master    
 auth_token:
  secure: kW2dq5Hyg8WlsGniBQ7Xs9c0AM7teybE4HjQcig8Jaw4yeGvoOqkQ49wUTvmKL08
# '%appveyorGithub%'
 artifact: build\Release\say_hello_addon_win32.tar.gz
 on:
  appveyor_repo_tag: false
  configuration: Release